org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.newDsl=false
kotlin.incremental=false
kotlin.incremental.java=false
android.enableR8.fullMode=true
android.enableResourceOptimizations=true
